### ISSUE TITLE
[MLX «Convert Guest To User»]: «Zend_XmlRpc_Client_HttpException: Not Found in lib/Zend/XmlRpc/Client.php:294»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [thehcginstitute-com/m1#14]
```
#0 lib/Zend/XmlRpc/Client.php(378): Zend_XmlRpc_Client->doRequest(Object(Zend_XmlRpc_Request))
#1 app/code/local/Mlx/Mlx/Model/Keygen.php(1) : eval()'d code(115): Zend_XmlRpc_Client->call('login', Array)
#2 app/code/local/Mlx/Mlx/Model/Observer.php(1) : eval()'d code(26): Mlx_Mlx_Model_Keygen->active('NTg5YWZmMTFjMGI...', 'Gconvert', 'thehcginstitute...')
#3 app/code/local/Mlx/Mlx/Model/Observer.php(1) : eval()'d code(50): Mlx_Mlx_Model_Observer->parse()
#4 app/code/core/Mage/Core/Model/App.php(1339): Mlx_Mlx_Model_Observer->controllerActionPredispatch(Object(Varien_Event_Observer))
#5 app/code/core/Mage/Core/Model/App.php(1318): Mage_Core_Model_App->_callObserverMethod(Object(Mlx_Mlx_Model_Observer), 'controllerActio...', Object(Varien_Event_Observer))
#6 app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#7 app/code/core/Mage/Core/Controller/Varien/Action.php(527): Mage::dispatchEvent('controller_acti...', Array)
#8 app/code/core/Mage/Adminhtml/Controller/Action.php(167): Mage_Core_Controller_Varien_Action->preDispatch()
#9 app/code/core/Mage/Core/Controller/Varien/Action.php(407): Mage_Adminhtml_Controller_Action->preDispatch()
#10 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#11 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 app/Mage.php(683): Mage_Core_Model_App->run(Array)
#14 index.php(94): Mage::run('', 'store')
#15 {main}
```

**Comment by dmitrii-fediuk** [comment]
[mlx-store.com/magento-extensions/sales/convert-guest-to-user.html](https://www.mlx-store.com/magento-extensions/sales/convert-guest-to-user.html)

**Comment by dmitrii-fediuk** [comment]
The error is occured because MLX has stopped to serve the `http://www.mlx-store.com/index.php/api/xmlrpc/` request.  
The MLX «Convert Guest To User» module's PHP code is encrypted, so I can not modify it.
But the module seems to be working even without a correct licence checking. 
![2023-12-16--19-11-10](https://github.com/thehcginstitute-com/m1/assets/83204/32963493-07ff-4f65-9060-0a585dcefd51)
