### ISSUE TITLE
«Error during unserialization in lib/Unserialize/Parser.php:59» on a customer login

### ISSUE THREAD

**Issue by dmitrii-fediuk** [thehcginstitute-com/m1#18]
```
#0 app/code/core/Mage/Core/Helper/UnserializeArray.php(44): Unserialize_Parser->unserialize('43,34')
#1 app/code/core/Mage/Sales/Model/Quote/Item.php(502): Mage_Core_Helper_UnserializeArray->unserialize('43,34')
#2 app/code/core/Mage/Sales/Model/Quote.php(1759): Mage_Sales_Model_Quote_Item->compare(Object(Mage_Sales_Model_Quote_Item))
#3 app/code/core/Mage/Checkout/Model/Session.php(216): Mage_Sales_Model_Quote->merge(Object(Mage_Sales_Model_Quote))
#4 app/code/core/Mage/Checkout/Model/Observer.php(44): Mage_Checkout_Model_Session->loadCustomerQuote()
#5 app/code/core/Mage/Core/Model/App.php(1339): Mage_Checkout_Model_Observer->loadCustomerQuote(Object(Varien_Event_Observer))
#6 app/code/core/Mage/Core/Model/App.php(1318): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Checkout_Model_Observer), 'loadCustomerQuo...', Object(Varien_Event_Observer))
#7 app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('customer_login', Array)
#8 app/code/local/Mage/Customer/Model/Session.php(227): Mage::dispatchEvent('customer_login', Array)
#9 app/code/local/Mage/Customer/Model/Session.php(215): Mage_Customer_Model_Session->setCustomerAsLoggedIn(Object(Mage_Customer_Model_Customer))
#10 app/code/community/SyncIt/FrontendLogs/controllers/Account/Frontend/Customer/AccountController.php(74): Mage_Customer_Model_Session->login('sharonmike@hotm...', 'q!S59SHngUiwHeD')
#11 app/code/core/Mage/Core/Controller/Varien/Action.php(418): SyncIt_FrontendLogs_Account_Frontend_Customer_AccountController->loginPostAction()
#12 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('loginPost')
#13 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#14 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#15 app/Mage.php(683): Mage_Core_Model_App->run(Array)
#16 index.php(94): Mage::run('', 'store')
#17 {main}
```

**Comment by dmitrii-fediuk** [comment]
Fixed by https://github.com/thehcginstitute-com/m1/issues/298
