### ISSUE TITLE
[MLX «Convert Guest To User»]: «Zend_XmlRpc_Client_HttpException: Not Found in lib/Zend/XmlRpc/Client.php:294» on the `/admin/mlx_license/index/` page

### ISSUE THREAD

**Issue by dmitrii-fediuk** [thehcginstitute-com/m1#386]
Similar to https://github.com/thehcginstitute-com/m1/issues/14

```
2024-02-19T02:23:14+00:00 ERR (3): 
Zend_XmlRpc_Client_HttpException: Not Found in vendor\shardj\zf1-future\library\Zend\XmlRpc\Client.php:294
Stack trace:
#0 vendor\shardj\zf1-future\library\Zend\XmlRpc\Client.php(378): Zend_XmlRpc_Client->doRequest(Object(Zend_XmlRpc_Request))
#1 app\code\local\Mlx\Mlx\Model\Keygen.php(1) : eval()'d code(161): Zend_XmlRpc_Client->call('login', Array)
#2 app\code\local\Mlx\Mlx\Block\Adminhtml\License.php(1) : eval()'d code(72): Mlx_Mlx_Model_Keygen->info('NTg5YWZmMTFjMGI...', 'Gconvert')
#3 app\design\adminhtml\default\default\template\Mlx\Mlx\license.phtml(26): Mlx_Mlx_Block_Adminhtml_License->getLicenseInfo('NTg5YWZmMTFjMGI...', 'Gconvert')
#4 app\code\core\Mage\Core\Block\Template.php(251): include('C:\\work\\clients...')
#5 app\code\core\Mage\Core\Block\Template.php(288): Mage_Core_Block_Template->fetchView('adminhtml\\defau...')
#6 app\code\core\Mage\Core\Block\Template.php(301): Mage_Core_Block_Template->renderView()
#7 app\code\core\Mage\Adminhtml\Block\Template.php(68): Mage_Core_Block_Template->_toHtml()
#8 app\code\core\Mage\Core\Block\Abstract.php(927): Mage_Adminhtml_Block_Template->_toHtml()
#9 app\code\core\Mage\Core\Block\Text\List.php(36): Mage_Core_Block_Abstract->toHtml()
#10 app\code\core\Mage\Core\Block\Abstract.php(927): Mage_Core_Block_Text_List->_toHtml()
#11 app\code\core\Mage\Core\Block\Abstract.php(644): Mage_Core_Block_Abstract->toHtml()
#12 app\code\core\Mage\Core\Block\Abstract.php(588): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#13 app\design\adminhtml\default\default\template\page.phtml(63): Mage_Core_Block_Abstract->getChildHtml('content')
#14 app\code\core\Mage\Core\Block\Template.php(251): include('C:\\work\\clients...')
#15 app\code\core\Mage\Core\Block\Template.php(288): Mage_Core_Block_Template->fetchView('adminhtml\\defau...')
#16 app\code\core\Mage\Core\Block\Template.php(301): Mage_Core_Block_Template->renderView()
#17 app\code\core\Mage\Adminhtml\Block\Template.php(68): Mage_Core_Block_Template->_toHtml()
#18 app\code\core\Mage\Core\Block\Abstract.php(927): Mage_Adminhtml_Block_Template->_toHtml()
#19 app\code\core\Mage\Core\Model\Layout.php(574): Mage_Core_Block_Abstract->toHtml()
#20 app\code\core\Mage\Core\Controller\Varien\Action.php(391): Mage_Core_Model_Layout->getOutput()
#21 app\code\local\Mlx\Mlx\controllers\Adminhtml\Mlx\LicenseController.php(1) : eval()'d code(14): Mage_Core_Controller_Varien_Action->renderLayout()
#22 app\code\core\Mage\Core\Controller\Varien\Action.php(422): Mlx_Mlx_Adminhtml_Mlx_LicenseController->indexAction()
#23 app\code\core\Mage\Core\Controller\Varien\Router\Standard.php(256): Mage_Core_Controller_Varien_Action->dispatch('index')
#24 app\code\core\Mage\Core\Controller\Varien\Front.php(182): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#25 app\code\core\Mage\Core\Model\App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#26 app\Mage.php(742): Mage_Core_Model_App->run(Array)
#27 index.php(62): Mage::run('', 'store')
#28 {main}

```

**Comment by dmitrii-fediuk** [comment]
```
[
	IP Address: 176.237.6.164
	OpenMage: 19.5.2
	PHP: 7.4.9
	Referer: https://localhost.com:2248/index.php/admin/sales_order/
	Request Method: GET
	URL: https://localhost.com:2248/index.php/admin/mlx_license/index/
	User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
]
EXCEPTION
Not Found
************************************
1	Zend_XmlRpc_Client::doRequest
	vendor/shardj/zf1-future/library/Zend/XmlRpc/Client.php:378

2	Zend_XmlRpc_Client::call
	app/code/local/Mlx/Mlx/Model/Keygen.php(1) : eval()'d code:161

3	Mlx_Mlx_Model_Keygen::info
	app/code/local/Mlx/Mlx/Block/Adminhtml/License.php(1) : eval()'d code:72

4	Mlx_Mlx_Block_Adminhtml_License::getLicenseInfo
	app/design/adminhtml/default/default/template/Mlx/Mlx/license.phtml:26

5	include
	app/code/core/Mage/Core/Block/Template.php:251

6	Mage_Core_Block_Template::fetchView
	app/code/core/Mage/Core/Block/Template.php:288

7	Mage_Core_Block_Template::renderView
	app/code/core/Mage/Core/Block/Template.php:301

8	Mage_Core_Block_Template::_toHtml
	app/code/core/Mage/Adminhtml/Block/Template.php:68

9	Mage_Adminhtml_Block_Template::_toHtml
	app/code/core/Mage/Core/Block/Abstract.php:927

10	Mage_Core_Block_Abstract::toHtml
	app/code/core/Mage/Core/Block/Text/List.php:36

11	Mage_Core_Block_Text_List::_toHtml
	app/code/core/Mage/Core/Block/Abstract.php:927

12	Mage_Core_Block_Abstract::toHtml
	app/code/core/Mage/Core/Block/Abstract.php:644

13	Mage_Core_Block_Abstract::_getChildHtml
	app/code/core/Mage/Core/Block/Abstract.php:588

14	Mage_Core_Block_Abstract::getChildHtml
	app/design/adminhtml/default/default/template/page.phtml:63

15	include
	app/code/core/Mage/Core/Block/Template.php:251

16	Mage_Core_Block_Template::fetchView
	app/code/core/Mage/Core/Block/Template.php:288

17	Mage_Core_Block_Template::renderView
	app/code/core/Mage/Core/Block/Template.php:301

18	Mage_Core_Block_Template::_toHtml
	app/code/core/Mage/Adminhtml/Block/Template.php:68

19	Mage_Adminhtml_Block_Template::_toHtml
	app/code/core/Mage/Core/Block/Abstract.php:927

20	Mage_Core_Block_Abstract::toHtml
	app/code/core/Mage/Core/Model/Layout.php:574

21	Mage_Core_Model_Layout::getOutput
	app/code/core/Mage/Core/Controller/Varien/Action.php:391

22	Mage_Core_Controller_Varien_Action::renderLayout
	app/code/local/Mlx/Mlx/controllers/Adminhtml/Mlx/LicenseController.php(1) : eval()'d code:14

23	Mlx_Mlx_Adminhtml_Mlx_LicenseController::indexAction
	app/code/core/Mage/Core/Controller/Varien/Action.php:422

24	Mage_Core_Controller_Varien_Action::dispatch
	app/code/core/Mage/Core/Controller/Varien/Router/Standard.php:256

25	Mage_Core_Controller_Varien_Router_Standard::match
	app/code/core/Mage/Core/Controller/Varien/Front.php:182

26	Mage_Core_Controller_Varien_Front::dispatch
	app/code/core/Mage/Core/Model/App.php:365

27	Mage_Core_Model_App::run
	app/Mage.php:742

28	Mage::run
	index.php:62



1	Zend_XmlRpc_Client::doRequest
	vendor/shardj/zf1-future/library/Zend/XmlRpc/Client.php:294

2	Zend_XmlRpc_Client::call
	vendor/shardj/zf1-future/library/Zend/XmlRpc/Client.php:378

3	Mlx_Mlx_Model_Keygen::info
	app/code/local/Mlx/Mlx/Model/Keygen.php(1) : eval()'d code:161

4	Mlx_Mlx_Block_Adminhtml_License::getLicenseInfo
	app/code/local/Mlx/Mlx/Block/Adminhtml/License.php(1) : eval()'d code:72

5	include
	app/design/adminhtml/default/default/template/Mlx/Mlx/license.phtml:26

6	Mage_Core_Block_Template::fetchView
	app/code/core/Mage/Core/Block/Template.php:251

7	Mage_Core_Block_Template::renderView
	app/code/core/Mage/Core/Block/Template.php:288

8	Mage_Core_Block_Template::_toHtml
	app/code/core/Mage/Core/Block/Template.php:301

9	Mage_Adminhtml_Block_Template::_toHtml
	app/code/core/Mage/Adminhtml/Block/Template.php:68

10	Mage_Core_Block_Abstract::toHtml
	app/code/core/Mage/Core/Block/Abstract.php:927

11	Mage_Core_Block_Text_List::_toHtml
	app/code/core/Mage/Core/Block/Text/List.php:36

12	Mage_Core_Block_Abstract::toHtml
	app/code/core/Mage/Core/Block/Abstract.php:927

13	Mage_Core_Block_Abstract::_getChildHtml
	app/code/core/Mage/Core/Block/Abstract.php:644

14	Mage_Core_Block_Abstract::getChildHtml
	app/code/core/Mage/Core/Block/Abstract.php:588

15	include
	app/design/adminhtml/default/default/template/page.phtml:63

16	Mage_Core_Block_Template::fetchView
	app/code/core/Mage/Core/Block/Template.php:251

17	Mage_Core_Block_Template::renderView
	app/code/core/Mage/Core/Block/Template.php:288

18	Mage_Core_Block_Template::_toHtml
	app/code/core/Mage/Core/Block/Template.php:301

19	Mage_Adminhtml_Block_Template::_toHtml
	app/code/core/Mage/Adminhtml/Block/Template.php:68

20	Mage_Core_Block_Abstract::toHtml
	app/code/core/Mage/Core/Block/Abstract.php:927

21	Mage_Core_Model_Layout::getOutput
	app/code/core/Mage/Core/Model/Layout.php:574

22	Mage_Core_Controller_Varien_Action::renderLayout
	app/code/core/Mage/Core/Controller/Varien/Action.php:391

23	Mlx_Mlx_Adminhtml_Mlx_LicenseController::indexAction
	app/code/local/Mlx/Mlx/controllers/Adminhtml/Mlx/LicenseController.php(1) : eval()'d code:14

24	Mage_Core_Controller_Varien_Action::dispatch
	app/code/core/Mage/Core/Controller/Varien/Action.php:422

25	Mage_Core_Controller_Varien_Router_Standard::match
	app/code/core/Mage/Core/Controller/Varien/Router/Standard.php:256

26	Mage_Core_Controller_Varien_Front::dispatch
	app/code/core/Mage/Core/Controller/Varien/Front.php:182

27	Mage_Core_Model_App::run
	app/code/core/Mage/Core/Model/App.php:365

28	Mage::run
	app/Mage.php:742
```

**Comment by dmitrii-fediuk** [comment]
Solved by https://github.com/thehcginstitute-com/m1/issues/389
