### ISSUE TITLE
«Argument 1 passed to iterator_to_array() must implement interface Traversable, instance of Closure given in app/code/local/Df/Core/lib/array/main.php:37»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [thehcginstitute-com/m1#454]
```
OpenMage: 19.5.2
PHP: 7.4.33
IP Address: 172.70.134.55
Request Method: POST
URL: https://www.thehcginstitute.com/store/api/xmlrpc
User-Agent: Zapier
File: app/code/local/Df/Core/lib/array/main.php
Line: 37
************************************
[E_ERROR] Uncaught TypeError: Argument 1 passed to iterator_to_array() must implement interface Traversable, instance of Closure given in app/code/local/Df/Core/lib/array/main.php:37
Stack trace:
#0 app/code/local/Df/Core/lib/array/main.php(37): iterator_to_array()
#1 app/code/local/Df/Core/lib/array/clean/filter.php(41): df_ita()
#2 app/code/local/Df/Core/lib/array/clean/filter.php(18): df_filter_f()
#3 app/code/local/Df/Core/lib/array/clean/main.php(63): df_filter()
#4 app/code/local/Df/Core/lib/array/clean/main.php(43): df_clean_r()
#5 app/code/local/Df/Core/lib/text/concatenate.php(75): df_clean()
#6 app/code/local/Df/Core/lib/reflection/text/cc.php(14): df_ccc()
#7 /home/thehcg-prod/public_html/store/app/code/local/Df/Core/lib/call
```

**Comment by dmitrii-fediuk** [comment]
```
OpenMage: 19.5.2
PHP: 7.4.9
IP Address: 176.237.6.164
Referer: https://localhost.com:2248/index.php/admin/sales_order_create/index/customer_id/4108/
Request Method: POST
URL: https://localhost.com:2248/index.php/admin/sales_order_create/save/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Post: 
{
    "billing_country_id": "",
    "billing_postcode": "",
    "billing_regione": "",
    "coupon_code": "",
    "email": "",
    "entity_id": "",
    "form_key": "osisQYyl8BVOeGMa",
    "in_products": "",
    "item": {
        "84432": {
            "action": "",
            "qty": "1",
            "use_discount": "1"
        }
    },
    "iwd_om_custom_amount": "",
    "iwd_om_custom_amount_desc": "",
    "limit": "20",
    "name": "",
    "order": {
        "account": {
            "dob": "7/8/1982",
            "email": "admin@mage2.pro",
            "gender": "1",
            "visitorid": ""
        },
        "billing_address": {
            "city": "\tNew York City\t",
            "company": "",
            "country_id": "US",
            "customer_address_id": "11280",
            "fax": "",
            "firstname": "Dmitrii",
            "lastname": "Fediuk",
            "middlename": "",
            "postcode": "10001",
            "prefix": "",
            "region": "",
            "region_id": "43",
            "street": [
                "49 West 32nd Street",
                ""
            ],
            "suffix": "",
            "telephone": "+1 (212) 736-3800",
            "vat_id": ""
        },
        "comment": {
            "customer_note": ""
        },
        "currency": "USD",
        "send_confirmation": "1",
        "shipping_method": "flatrate_flatrate"
    },
    "page": "1",
    "payment": {
        "method": "free"
    },
    "price": {
        "from": "",
        "to": ""
    },
    "shipping_as_billing": "1",
    "sku": "",
    "store_name": "",
    "Telephone": ""
}
File: app/code/local/Df/Core/lib/array/main.php
Line: 37
************************************
[E_ERROR] Uncaught TypeError: Argument 1 passed to iterator_to_array() must implement interface Traversable, instance of Closure given in app/code/local/Df/Core/lib/array/main.php:37
Stack trace:
#0 app/code/local/Df/Core/lib/array/main.php(37): iterator_to_array(Object(Closure))
#1 app/code/local/Df/Core/lib/array/clean/filter.php(41): df_ita(Object(Closure))
#2 app/code/local/Df/Core/lib/array/clean/filter.php(18): df_filter_f(Array, Object(Closure), 'array_filter')
#3 app/code/local/Df/Core/lib/array/clean/main.php(63): df_filter(Array, Object(Closure))
#4 app/code/local/Df/Core/lib/array/clean/main.php(43): df_clean_r(Array, Array, false)
#5 C:\work\clients\thehcginstitute.com\m\2023-11-21\code\ap
```
