### ISSUE TITLE
«Call to a member function getParentItem() on null in app/design/frontend/base/default/template/sales/order/invoice/items.phtml:42»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [thehcginstitute-com/m1#511]
```
OpenMage: 19.5.2
PHP: 7.4.33
Customer ID: 1737
IP Address: 172.71.151.113
Referer: https://www.thehcginstitute.com/store/sales/order/view/order_id/17455/
Request Method: GET
URL: https://www.thehcginstitute.com/store/sales/order/invoice/order_id/17455/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.3.1 Safari/605.1.15
File: app/design/frontend/base/default/template/sales/order/invoice/items.phtml
Line: 42
************************************
[E_ERROR] Uncaught Error: Call to a member function getParentItem() on null in app/design/frontend/base/default/template/sales/order/invoice/items.phtml:42
Stack trace:
#0 app/code/core/Mage/Core/Block/Template.php(251): include()
#1 app/code/core/Mage/Core/Block/Template.php(288): Mage_Core_Block_Template->fetchView('frontend/base/d...')
#2 app/code/core/Mage/Core/Block/Template.php(301): Mage_Core_Block_Template->renderView()
#3 app/code/core/Mage/Core/Block/Abstract.php(927): Mage_Core_Block_Template->_toHtml()
#4 app/code/core/Mage/Core/Block/Abstract.php(644): Mage_Core_Block_Abstract->toHtml()
#5 app/code/core/Mage/Core/Block/Abstract.php(588): Mage_Core_Block_Abstract->_getChildHtml('invoice_items', true)
#6 app/design/frontend/b
```

**Comment by dmitrii-fediuk** [comment]
![Uploading 2024-03-17--11-06-09.png…]()
