### ISSUE TITLE
«The requested Payment Method is not available» on viewing an order paid via a deleted payment module

### ISSUE THREAD

**Issue by dmitrii-fediuk** [thehcginstitute-com/m1#52]
Caused by https://github.com/thehcginstitute-com/m1/issues/47

**Comment by dmitrii-fediuk** [comment]
```
2023-12-16T16:31:01+00:00 ERR (3): 
Mage_Core_Exception: The requested Payment Method is not available. in app\Mage.php:595
Stack trace:
#0 app\code\core\Mage\Payment\Model\Info.php(82): Mage::throwException('The requested P...')
#1 app\code\core\Mage\Adminhtml\Block\Sales\Order\View.php(95): Mage_Payment_Model_Info->getMethodInstance()
#2 app\code\core\Mage\Core\Model\Layout.php(491): Mage_Adminhtml_Block_Sales_Order_View->__construct(Array)
#3 app\code\core\Mage\Core\Model\Layout.php(437): Mage_Core_Model_Layout->_getBlockInstance('Mage_Adminhtml_...', Array)
#4 app\code\core\Mage\Core\Model\Layout.php(472): Mage_Core_Model_Layout->createBlock('adminhtml/sales...', 'sales_order_edi...')
#5 app\code\core\Mage\Core\Model\Layout.php(239): Mage_Core_Model_Layout->addBlock('adminhtml/sales...', 'sales_order_edi...')
#6 app\code\core\Mage\Core\Model\Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#7 app\code\core\Mage\Core\Model\Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#8 app\code\core\Mage\Core\Controller\Varien\Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#9 app\code\core\Mage\Core\Controller\Varien\Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#10 app\code\core\Mage\Adminhtml\Controller\Action.php(285): Mage_Core_Controller_Varien_Action->loadLayout(NULL, true, true)
#11 app\code\core\Mage\Adminhtml\controllers\Sales\OrderController.php(59): Mage_Adminhtml_Controller_Action->loadLayout()
#12 app\code\core\Mage\Adminhtml\controllers\Sales\OrderController.php(124): Mage_Adminhtml_Sales_OrderController->_initAction()
#13 app\code\core\Mage\Core\Controller\Varien\Action.php(418): Mage_Adminhtml_Sales_OrderController->viewAction()
#14 app\code\core\Mage\Core\Controller\Varien\Router\Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('view')
#15 app\code\core\Mage\Core\Controller\Varien\Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#16 app\code\core\Mage\Core\Model\App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#17 app\Mage.php(683): Mage_Core_Model_App->run(Array)
#18 index.php(94): Mage::run('', 'store')
#19 {main}
```
