### ISSUE TITLE
«Call to a member function setInfo() on bool in app/code/core/Mage/Payment/Helper/Data.php:131» on the `customer/account` page

### ISSUE THREAD

**Issue by dmitrii-fediuk** [thehcginstitute-com/m1#554]
```
OpenMage: 19.5.2
PHP: 7.4.33
Customer ID: 15812
IP Address: 162.158.62.111
Referer: https://www.thehcginstitute.com/store/customer/account/
Request Method: GET
URL: https://www.thehcginstitute.com/store/sales/order/view/order_id/17716/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
File: app/code/core/Mage/Payment/Helper/Data.php
Line: 131
************************************
[E_ERROR] Uncaught Error: Call to a member function setInfo() on bool in app/code/core/Mage/Payment/Helper/Data.php:131
Stack trace:
#0 app/code/core/Mage/Sales/Block/Order/Info.php(48): Mage_Payment_Helper_Data->getInfoBlock(Object(Mage_Sales_Model_Order_Payment))
#1 app/code/core/Mage/Core/Block/Abstract.php(300): Mage_Sales_Block_Order_Info->_prepareLayout()
#2 app/code/core/Mage/Core/Model/Layout.php(475): Mage_Core_Block_Abstract->setLayout(Object(Df_Core_Model_Layout))
#3 app/code/core/Mage/Core/Model/Layout.php(491): Mage_Core_Model_Layout->createBlock('sales/order_inf...', 'sales.order.inf...')
#4 app/code/core/Mage/Core/Model/Layout.php(235): Mage_Core_Model_Layout->addBlock('sales/order_inf...', 'sales.order.inf...')
#5 app/code/core/Mage/Core/Model/Layout.php(2
```

**Comment by dmitrii-fediuk** [comment]
![2024-04-12--23-15-24](https://github.com/thehcginstitute-com/m1/assets/83204/87306630-be3e-4c3f-9573-08addddf5146)

**Comment by dmitrii-fediuk** [comment]
Solved by https://github.com/thehcginstitute-com/m1/issues/558
